name: ABMCMultiWarp
version: 1.0
main: server.alanbecker.net.Warps
api-version: 1.13
author: MasterGabeMOD

commands:
  rwarp:
    description: Access the random warp commands or create a new warp
    usage: "/rwarp <create|warpName>"
  setpoint:
    description: Set a point for a specific warp
    usage: "/setpoint <warpName>"

permissions:
  abmc.create.rwarp:
    description: Allows creation of new warps
    default: op
  abmc.create.setpoint:
    description: Allows setting points for warps
    default: op
  abmc.rwarp.teleport:
    description: Allows teleporting to warps
    default: true
