name: ABMCMultiWarp
version: 1.2
main: server.alanbecker.net.Warps
api-version: 1.13
author: MasterGabeMOD
commands:
  rwarp:
    description: Access the random warp commands, create a new warp, list all warps, or reload the configuration
    usage: "/rwarp <create|warpName|list|reload>"
  setpoint:
    description: Set a point for a specific warp
    usage: "/setpoint <warpName>"
permissions:
  abmc.create.rwarp:
    description: Allows creation of new warps
    default: op
  abmc.create.setpoint:
    description: Allows setting points for warps
    default: op
  abmc.rwarp.teleport:
    description: Allows teleporting to warps
    default: true
  abmc.rwarp.list:
    description: Allows listing all available warps
    default: true
  abmc.bypass.cooldown:
    description: Allows bypassing the cooldown for warps
    default: op
  abmc.rwarp.reload:
    description: Allows reloading the configuration
    default: op
